import { Rajdhani } from 'next/font/google'
import './globals.css'
import NavBar from './components/NavBar/NavBar'
import Head from 'next/head'

const rajdhani = Rajdhani({ subsets: ['latin'], weight: '400' })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      
      <body className={rajdhani.className}>
      <NavBar></NavBar> 
        {children}</body>
    </html>
  )
}
